other file

diff --git a/module2_task1/Makefile b/module2_task1/Makefile
--- a/module2_task1/Makefile
+++ b/module2_task1/Makefile
@@ -1,50 +1,43 @@
-# Makefile for Golang HTTP web server project
-
+# Variables
 BINARY_NAME := awesome-api
-LOG_FILE := awesome-api.log
+LOG_FILE := $(BINARY_NAME).log
+PID_FILE := $(BINARY_NAME).pid
 
-.PHONY: all build run stop clean test help lint
+# Goals
+.PHONY: help
 
-lint: ## Runs static analysis on the source code using golangci-lint.
-	@echo "Running lint..."
-	@golangci-lint run
+help: ## Prints out the list of targets and their usage
+	@awk 'BEGIN {FS = ":.*?# "} /^[a-zA-Z_-]+:.*?# / {printf "\033[36m%-10s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
 
-all: lint build ## This is the default target that depends on the build target. It compiles the source
 
-build: ## Compiles the source code into an executable binary named awesome-api.
-	@echo "Building the binary..."
-	@go build -o $(BINARY_NAME) .
-	@hugo
+.PHONY: build
+build: lint ## alsdjflksajdf a;ljsdflsadhf hf hdsa;lahdsf sdf;lkahds fhdsaf
+	go get github.com/gorilla/mux
+	go build -o $(BINARY_NAME)
 
-post: ## Creates a new post for the web server using Hugo. Provide the POST_NAME and POST_TITLE variables to specify the post's name and title, respectively.
-	@hugo new posts/$(POST_NAME).md
-	@sed -i 's/title: .*/title: "$(POST_TITLE)"/' content/posts/$(POST_NAME).md
+.PHONY: run 
+run: ## dslfjsaldjflkdsajfsajf;ljsadjf;lsajdfkldsaf sadfasdfasdfdsa
+	./$(BINARY_NAME) > $(LOG_FILE) 2>&1 & echo $$! > $(PID_FILE)
 
-run: ## Runs the compiled application in the background, redirecting the output to the awesome-api.log file.
-	@echo "Running the application in the background..."
-	@./$(BINARY_NAME) > $(LOG_FILE) 2>&1 &
+.PHONY: stop
+stop: ## dsakjhfalsd hf;lsa fjdsahf;sahfhsadlkfhsadfsafd 
+	-kill `cat $(PID_FILE)` || true
+	-rm $(PID_FILE) || true
 
-stop: ##  Stops the running application by killing the process using the pgrep and kill commands.
-	@echo "Stopping the application..."
-	@kill `pgrep $(BINARY_NAME)`
 
-clean: ## Cleans up binary files, log files, and kills any running instances of the awesome-api process.
-	@echo "Cleaning up..."
-	@rm -f $(BINARY_NAME) $(LOG_FILE)
-	@pkill awesome-api
-	@rm -rf ./dist/*
+.PHONY: clean 
+clean: ## sa;lkdjf dsasadlkjfsad f;lj hdsaflja'skjd flkas
+	make stop
+	-rm $(BINARY_NAME) || true
+	-rm $(LOG_FILE) || true
 
-test: ## Performs basic tests on the application by sending HTTP requests
-	@echo "Testing the application..."
-	@curl http://localhost:9999
-	@curl http://localhost:9999/health
+.PHONY: test
+test: ## WOOOHOOOOOOOO saljdfasldhfaksdf asdsafgasgasfasdf
+	@echo "Testing HTTP endpoint /..."
+	@curl -sSf http://localhost:9999 || echo "TESTFAILED"
+	@echo "Testing HTTP endpoint /health..."
+	@curl -sSf http://localhost:9999/health || echo "TESTFAILED"
 
-help: ## Prints out the list of targets and their usage.
-	@echo "Available targets:"
-	@echo "  all:       compile and run the application (default)"
-	@echo "  build:     compile the source code to a binary"
-	@echo "  run:       run the application"
-	@echo "  stop:      stop the running application"
-	@echo "  clean:     clean up the binary and log file"
-	@echo "  test:      test the application"
-	@echo "  lint:      run static analysis on the source code"
+.PHONY: lint
+lint: ## LINT LINT LINT YEAHHHH BABYYYY
+	golangci-lint run
